import {
  ShoppingCart,
  Home,
  Briefcase,
  Utensils,
  Car,
  Zap,
  Film,
  Heart,
  Gift,
  Phone,
  Wifi,
  CreditCard,
  Plane,
  GraduationCap,
  Dumbbell,
  Music,
  Gamepad2,
  ShoppingBag,
  Coffee,
  Baby,
  Dog,
  Shirt,
  Scissors,
  Wrench,
  Fuel,
  Bus,
  Train,
  Bike,
  Pill,
  Stethoscope,
  BookOpen,
  Newspaper,
  Tv,
  Camera,
  Palette,
  Sparkles,
  Banknote,
  PiggyBank,
  TrendingUp,
  Receipt,
  Tag,
  Wallet,
  CircleDollarSign,
  HandCoins,
  Landmark,
  Building2,
  Store,
  Warehouse,
  Key,
  Lock,
  Shield,
  Globe,
  Map,
  MapPin,
  Navigation,
  Compass,
  Mountain,
  Trees,
  Umbrella,
  Sun,
  Moon,
  Cloud,
  Snowflake,
  Droplets,
  Flame,
  Wind,
  Leaf,
  Flower2,
  Apple,
  Beef,
  Egg,
  IceCreamCone,
  Wine,
  Beer,
  CupSoda,
  Sandwich,
  Pizza,
  Soup,
  Salad,
  Popcorn,
  Cake,
  Cookie,
  Croissant,
  Cat,
  Bird,
  Fish,
  Bug,
  Rabbit,
  Turtle,
  Footprints,
  Bed,
  Bath,
  Lamp,
  Sofa,
  Armchair,
  DoorOpen,
  Paintbrush,
  Hammer,
  Drill,
  HardHat,
  Truck,
  Ship,
  Rocket,
  Cable,
  Bluetooth,
  Monitor,
  Laptop,
  Smartphone,
  Tablet,
  Watch,
  Headphones,
  Speaker,
  Printer,
  Keyboard,
  Mouse,
  Cpu,
  HardDrive,
  Usb,
  Battery,
  Plug,
  Lightbulb,
  Clock,
  Timer,
  AlarmClock,
  Calendar,
  CalendarDays,
  FileText,
  FolderOpen,
  Archive,
  Inbox,
  Mail,
  Send,
  MessageCircle,
  Bell,
  Megaphone,
  Flag,
  Bookmark,
  Star,
  Award,
  Trophy,
  Medal,
  Crown,
  Gem,
  Diamond,
  Glasses,
  Eye,
  Ear,
  Hand,
  ThumbsUp,
  Smile,
  Frown,
  Angry,
  PartyPopper,
  Ribbon,
  Wand2,
  Dice5,
  Puzzle,
  Target,
  Crosshair,
  Swords,
  ShieldCheck,
  Siren,
  CircleAlert,
  Info,
  HelpCircle,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  // Shopping & Money
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  "store": Store,
  "tag": Tag,
  "receipt": Receipt,
  "banknote": Banknote,
  "wallet": Wallet,
  "circle-dollar-sign": CircleDollarSign,
  "hand-coins": HandCoins,
  "piggy-bank": PiggyBank,
  "credit-card": CreditCard,
  "trending-up": TrendingUp,
  "landmark": Landmark,

  // Home & Living
  "home": Home,
  "building-2": Building2,
  "warehouse": Warehouse,
  "key": Key,
  "bed": Bed,
  "bath": Bath,
  "lamp": Lamp,
  "sofa": Sofa,
  "armchair": Armchair,
  "door-open": DoorOpen,

  // Food & Drink
  "utensils": Utensils,
  "coffee": Coffee,
  "apple": Apple,
  "beef": Beef,
  "egg": Egg,
  "ice-cream-cone": IceCreamCone,
  "wine": Wine,
  "beer": Beer,
  "cup-soda": CupSoda,
  "sandwich": Sandwich,
  "pizza": Pizza,
  "soup": Soup,
  "salad": Salad,
  "popcorn": Popcorn,
  "cake": Cake,
  "cookie": Cookie,
  "croissant": Croissant,

  // Transport
  "car": Car,
  "fuel": Fuel,
  "bus": Bus,
  "train": Train,
  "bike": Bike,
  "plane": Plane,
  "truck": Truck,
  "ship": Ship,
  "rocket": Rocket,
  "navigation": Navigation,

  // Work & Education
  "briefcase": Briefcase,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  "newspaper": Newspaper,
  "file-text": FileText,
  "folder-open": FolderOpen,
  "archive": Archive,

  // Health & Fitness
  "pill": Pill,
  "stethoscope": Stethoscope,
  "dumbbell": Dumbbell,
  "heart": Heart,
  "shield-check": ShieldCheck,

  // Tech & Devices
  "monitor": Monitor,
  "laptop": Laptop,
  "smartphone": Smartphone,
  "tablet": Tablet,
  "watch": Watch,
  "headphones": Headphones,
  "speaker": Speaker,
  "printer": Printer,
  "keyboard": Keyboard,
  "mouse": Mouse,
  "cpu": Cpu,
  "hard-drive": HardDrive,
  "usb": Usb,
  "cable": Cable,
  "bluetooth": Bluetooth,
  "wifi": Wifi,
  "phone": Phone,
  "tv": Tv,

  // Utilities & Home Services
  "zap": Zap,
  "lightbulb": Lightbulb,
  "plug": Plug,
  "battery": Battery,
  "droplets": Droplets,
  "flame": Flame,
  "wind": Wind,

  // Entertainment
  "film": Film,
  "music": Music,
  "gamepad-2": Gamepad2,
  "camera": Camera,
  "palette": Palette,
  "dice-5": Dice5,
  "puzzle": Puzzle,
  "party-popper": PartyPopper,

  // People & Pets
  "baby": Baby,
  "dog": Dog,
  "cat": Cat,
  "bird": Bird,
  "fish": Fish,
  "bug": Bug,
  "rabbit": Rabbit,
  "turtle": Turtle,
  "footprints": Footprints,

  // Clothing & Personal
  "shirt": Shirt,
  "scissors": Scissors,
  "glasses": Glasses,
  "gem": Gem,
  "diamond": Diamond,
  "crown": Crown,
  "sparkles": Sparkles,

  // Tools & Maintenance
  "wrench": Wrench,
  "hammer": Hammer,
  "drill": Drill,
  "hard-hat": HardHat,
  "paintbrush": Paintbrush,

  // Nature & Weather
  "leaf": Leaf,
  "flower-2": Flower2,
  "trees": Trees,
  "mountain": Mountain,
  "sun": Sun,
  "moon": Moon,
  "cloud": Cloud,
  "snowflake": Snowflake,
  "umbrella": Umbrella,

  // Travel & Places
  "globe": Globe,
  "map": Map,
  "map-pin": MapPin,
  "compass": Compass,

  // Communication
  "mail": Mail,
  "send": Send,
  "message-circle": MessageCircle,
  "inbox": Inbox,
  "bell": Bell,
  "megaphone": Megaphone,

  // Time & Calendar
  "clock": Clock,
  "timer": Timer,
  "alarm": AlarmClock,
  "calendar": Calendar,
  "calendar-days": CalendarDays,

  // Gifts & Rewards
  "gift": Gift,
  "star": Star,
  "award": Award,
  "trophy": Trophy,
  "medal": Medal,
  "ribbon": Ribbon,
  "wand-2": Wand2,

  // Safety & Security
  "lock": Lock,
  "shield": Shield,
  "siren": Siren,
  "target": Target,
  "crosshair": Crosshair,
  "swords": Swords,

  // Info & Status
  "bookmark": Bookmark,
  "flag": Flag,
  "eye": Eye,
  "ear": Ear,
  "hand": Hand,
  "thumbs-up": ThumbsUp,
  "smile": Smile,
  "frown": Frown,
  "angry": Angry,
  "circle-alert": CircleAlert,
  "info": Info,
  "help-circle": HelpCircle,
};

export function getCategoryIcon(iconName: string | null): LucideIcon | null {
  if (!iconName) return null;
  return CATEGORY_ICONS[iconName] ?? null;
}
