import {
  ShoppingCart,
  Home,
  Briefcase,
  Utensils,
  Car,
  Zap,
  Film,
  Heart,
  Gift,
  Phone,
  Wifi,
  CreditCard,
  Plane,
  GraduationCap,
  Dumbbell,
  Music,
  Gamepad2,
  ShoppingBag,
  Coffee,
  Baby,
  Dog,
  Shirt,
  Scissors,
  Wrench,
  Fuel,
  Bus,
  Train,
  Bike,
  Pill,
  Stethoscope,
  BookOpen,
  Newspaper,
  Tv,
  Camera,
  Palette,
  Sparkles,
  Banknote,
  PiggyBank,
  TrendingUp,
  Receipt,
  Tag,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  "shopping-cart": ShoppingCart,
  "home": Home,
  "briefcase": Briefcase,
  "utensils": Utensils,
  "car": Car,
  "zap": Zap,
  "film": Film,
  "heart": Heart,
  "gift": Gift,
  "phone": Phone,
  "wifi": Wifi,
  "credit-card": CreditCard,
  "plane": Plane,
  "graduation-cap": GraduationCap,
  "dumbbell": Dumbbell,
  "music": Music,
  "gamepad-2": Gamepad2,
  "shopping-bag": ShoppingBag,
  "coffee": Coffee,
  "baby": Baby,
  "dog": Dog,
  "shirt": Shirt,
  "scissors": Scissors,
  "wrench": Wrench,
  "fuel": Fuel,
  "bus": Bus,
  "train": Train,
  "bike": Bike,
  "pill": Pill,
  "stethoscope": Stethoscope,
  "book-open": BookOpen,
  "newspaper": Newspaper,
  "tv": Tv,
  "camera": Camera,
  "palette": Palette,
  "sparkles": Sparkles,
  "banknote": Banknote,
  "piggy-bank": PiggyBank,
  "trending-up": TrendingUp,
  "receipt": Receipt,
  "tag": Tag,
};

export function getCategoryIcon(iconName: string | null): LucideIcon | null {
  if (!iconName) return null;
  return CATEGORY_ICONS[iconName] ?? null;
}
